# Sectopm 23 Numpy Arrays a Brief Introduction

#### Lecture 125 What does Numpy do?
#### Lecture 126 Creating Numpy Arrays
#### Lecture 127 Special Arrays and Matrices
#### Lecture 128 Resizing
#### Lecture 129 \*Random Number Generators (Oprional)
#### Lecture 130 \* Random Shuffling and Choices (Optional)
#### Lecture 131 Elementwise Computations in Numpy
#### Lecture 132 \* Some Matrix Math (Advance/Optional)
#### Lecture 133 Numpy's Indexing (IMPORTANT)

Numpy is a cornerstone for numeric computation and data science.

Numpy provides linear algebra capabilities/functionalities for Python
Numpy is not written in Python rather C or C++ - making it a lot faster.

In [1]:
import numpy as np

#### Lecture 126 - creating numpy arrays

In [3]:
# Create a 1 dim numpy array.  A single Vector
a = np.array([1.0, 2.0, 4.5, -10.3])
a

array([  1. ,   2. ,   4.5, -10.3])

In [4]:
a + 10

array([11. , 12. , 14.5, -0.3])

In [8]:
# Create 2 dim matrix

b = np.array([[1, 2, 3],[20.0, 5.4, -10.3], [4, 8, 3]])
b

array([[  1. ,   2. ,   3. ],
       [ 20. ,   5.4, -10.3],
       [  4. ,   8. ,   3. ]])

#### Lecture 127 Special Arrays and Matrices:

In [9]:
# Create an array of all 1s:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
# And with 2 dimensions:
# NB: Needs to be a tuple to work

np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# And a column of only 1s:
np.ones((5, 1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [14]:
# And an array of 0s

np.zeros((6, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# row of 10 0s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# Column of 10 0:
np.zeros((10, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
# Creating an Identity Matrix - must be square all must be zero except the main diagonal 1s
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Create a Siagonal Matrix - Must be square can be any value:
np.diag([10, 20, -80])

array([[ 10,   0,   0],
       [  0,  20,   0],
       [  0,   0, -80]])

#### Lecture 128 Resizing

In [21]:
# first create a simple array:

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [24]:
# Resize to 3 x 2 Matrix:

b = a.reshape(3, 2)

In [25]:
c = a.reshape(2, 3)

In [26]:
# And another way to do it:
np.reshape(a, (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Lecture 129 \*Random Number Generator (Optional)

In [31]:
# Integer Random Number Generation:
np.random.randint(low=1,high=7, size=10 ) # To replicate 10 throws of a die

array([6, 3, 5, 1, 1, 2, 5, 1, 3, 4])

In [33]:
# Float Random Number Generation Between 0 and 1:

np.random.rand(5)

array([0.72376057, 0.47835784, 0.37767186, 0.4566799 , 0.52545825])

In [35]:
# As above with uniform distribution specified:
np.random.uniform(0, 1, 50)

array([0.52147043, 0.67613154, 0.24123183, 0.61828679, 0.26321417,
       0.45547482, 0.41032009, 0.00636547, 0.85252568, 0.65995067,
       0.58084235, 0.36420224, 0.2676412 , 0.58566409, 0.98418957,
       0.51663419, 0.47147186, 0.03141479, 0.0793878 , 0.37119532,
       0.63542755, 0.34582553, 0.00807415, 0.69927646, 0.71895456,
       0.94535342, 0.77952729, 0.05788164, 0.16799846, 0.89109371,
       0.62025382, 0.31530576, 0.05617071, 0.71101041, 0.43771506,
       0.44688148, 0.22726636, 0.00573539, 0.34730428, 0.22097778,
       0.22709248, 0.20246145, 0.35247794, 0.88559459, 0.12859451,
       0.00740978, 0.16172272, 0.70012611, 0.69552047, 0.8185307 ])

In [40]:
# As above with uniform distribution specified in a 4 x 5 Array:
np.random.uniform(0, 1, 20).reshape(10, 2)

array([[3.67660819e-01, 2.92587506e-01],
       [2.60554391e-02, 3.68077076e-01],
       [3.20557062e-01, 5.34242784e-01],
       [1.32772819e-01, 4.20273467e-01],
       [5.13219091e-01, 8.45783883e-01],
       [2.86729763e-01, 4.19493895e-01],
       [8.05821930e-01, 1.28315021e-01],
       [2.32447766e-01, 5.79181529e-01],
       [6.36205967e-01, 7.05127823e-04],
       [8.07996140e-01, 2.07900898e-01]])

In [43]:
# Create a normal distribution:

np.random.standard_normal(24).reshape(4, 6)  # Mean 0 SD 1

array([[ 1.36412482,  0.18191409,  0.65479959,  0.3773635 , -0.54609726,
         0.85312504],
       [ 0.67919118, -0.28843572,  1.47537154,  0.64244914,  1.39429462,
        -1.45122894],
       [ 0.58607485, -0.24134237,  0.29964882, -0.02440098, -0.86186013,
         0.11473443],
       [-1.94516254, -1.35701322, -0.48807761,  0.38857773,  0.77777782,
         0.31778324]])

In [45]:
# Normal Distribution with a given mean or standard deviation:
# Arguments: Mean, STD, Number of items

np.random.normal(100, 10, 10)

array([106.52709049,  98.07973661,  93.68125525, 106.6645129 ,
       107.49843749, 111.27577316,  92.0260018 , 109.32039952,
       108.6346846 , 106.31299579])

In [46]:
# Log normal distribution:
# - Distribution that Stock Prices supposedly follow though in real life
# - stock prices have longer tails
# - Arguments as above.
np.random.lognormal(0.1, 0.3, 100)

array([0.83250324, 0.66077382, 1.31818074, 1.02539913, 0.67003692,
       1.83378765, 1.64398166, 2.35960793, 1.01788119, 2.36006181,
       0.86887959, 1.95146163, 1.3435601 , 1.35699088, 1.50877554,
       1.38082157, 0.71251956, 0.65415059, 0.72256028, 1.03904479,
       0.87885454, 1.30524583, 1.58716587, 1.33660387, 0.99069344,
       1.07423124, 1.07988908, 1.43774786, 1.35192217, 0.44756871,
       1.33104848, 1.03119598, 1.62027981, 1.29109286, 0.92338343,
       1.28472606, 0.65547203, 0.85311189, 1.57660017, 1.04733663,
       1.04644898, 1.53722858, 0.86843678, 1.53377975, 1.03234547,
       0.95333167, 0.5463033 , 1.27857563, 1.18165813, 1.27467334,
       0.91340794, 0.89086865, 1.09349888, 2.16606729, 1.46802064,
       1.25525649, 1.7267837 , 1.10368894, 0.94297205, 1.13813512,
       1.18138205, 0.95151339, 1.31231718, 0.80358637, 1.19768993,
       1.34369809, 1.10004438, 0.91733199, 1.12208793, 1.05629632,
       1.33185281, 1.13079404, 0.80795135, 0.7686909 , 0.99131

#### Lecture 130 \*Random Shuffling Choices (Optional)

In [47]:
cards: list = list(range(1, 14))
cards


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [49]:
# Shuffle the cards using nump's random shuffle function:
np.random.shuffle(cards)
cards

[3, 8, 10, 11, 7, 12, 1, 2, 13, 9, 4, 5, 6]

In [51]:
# Random Choice chooses an item from cards and shows it:
np.random.choice(cards)

8

In [52]:
# Also possible to choose the number of cards to choose:
np.random.choice(cards, 5)

array([4, 5, 6, 9, 7])

#### Lecture 131 Element-Wise Computations in Numpy:

In [53]:
a

array([1, 2, 3, 4, 5, 6])

In [55]:
# Simple element-wise computation:
# NB adding a scalar to a vector will broadcast it to evey element
a + 100

array([101, 102, 103, 104, 105, 106])

In [60]:
# Adding 1 vector to another:
# - Will be element-wise - element 1 will be added to element 1 etc.
# - Can do addition, multiplication, subtraction and division etc in this way
b = np.random.random(6)
b

array([0.20828558, 0.61259714, 0.16477419, 0.21009821, 0.18995308,
       0.68448655])

In [59]:
a + b

array([1.40903995, 2.74841439, 3.57401818, 4.97952585, 5.69622627,
       6.93821386])

In [64]:
A = np.arange(1, 13).reshape(3, 4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
B = np.arange(101, 113).reshape(3, 4)
B

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [68]:
A + B

array([[102, 104, 106, 108],
       [110, 112, 114, 116],
       [118, 120, 122, 124]])

In [70]:
# Note Scalar is being broadcast to all items in the multiplication part of the formula
(B/A) * 5

array([[505.        , 255.        , 171.66666667, 130.        ],
       [105.        ,  88.33333333,  76.42857143,  67.5       ],
       [ 60.55555556,  55.        ,  50.45454545,  46.66666667]])

#### Lecture 132 \*Some Matrix Math (Advanced/Optional)

In [71]:
# Matrix Multiplication:

X = np.array([[1, 2], [10, 4], [3, 7]])
X

array([[ 1,  2],
       [10,  4],
       [ 3,  7]])

In [76]:
Y = np.arange(4, 10).reshape(2, 3)
Y

array([[4, 5, 6],
       [7, 8, 9]])

In [79]:
X.shape

(3, 2)

In [80]:
Y.shape

(2, 3)

In [81]:
# The rightmost of shape of Y must be equal to the leftmost of X
np.matmul(X,Y)

array([[18, 21, 24],
       [68, 82, 96],
       [61, 71, 81]])

In [82]:
np.matmul(Y,X)

array([[ 72,  70],
       [114, 109]])

In [86]:
# Finding the determinant:

S = np.matmul(X,Y) + np.array([10, 20, -5])
S

array([[ 28,  41,  19],
       [ 78, 102,  91],
       [ 71,  91,  76]])

In [89]:
S_inv = np.linalg.inv(S)
S_inv

array([[-0.12288037, -0.32218351,  0.41649245],
       [ 0.12380952,  0.18095238, -0.24761905],
       [-0.03344948,  0.08432056, -0.07944251]])

In [90]:
np.matmul(S, S_inv)

array([[ 1.00000000e+00, -4.44089210e-16,  2.27595720e-15],
       [ 5.82867088e-16,  1.00000000e+00,  3.60822483e-15],
       [-1.22124533e-15, -8.88178420e-16,  1.00000000e+00]])

In [91]:
np.linalg.det(S)

4304.999999999992

#### Lecture 133 Numpy's Indexing (IMPORTANT)

In [92]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
# Indexing to find a certain value:
A[0, 0]

1

In [94]:
# Find the 11

A[2, 2]

11

In [96]:
# Find the 8

A[1, 3]

8

In [106]:
# Take out the first row:
A[0]

array([1, 2, 3, 4])

In [107]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
# Take one particular Column:
A[:,2]

array([ 3,  7, 11])

In [120]:
# Take out 6 and 7:

A[1,[1,2]]

array([6, 7])

In [122]:
# Or:
A[1,1:3]

array([6, 7])

In [124]:
# Get 8 and 12:
A[1:3,3]

array([ 8, 12])

In [126]:
# Or
A[1:,3]

array([ 8, 12])

In [131]:
# Get square 2, 3, 6, 7:

A[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [132]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [135]:
# Change 5 to 50
A[1,0] = 50
A

array([[ 1, 50,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
# Change a range of numbers in one hit (everything in the last row):

A[2:] = [59, 70, 112, 250]
A

array([[  1,  50,   3,   4],
       [ 50,   6,   7,   8],
       [ 59,  70, 112, 250]])

In [142]:
# If want all to be same number can broadcast:
A[0] = 0
A

array([[  0,   0,   0,   0],
       [ 50,   6,   7,   8],
       [ 59,  70, 112, 250]])

In [143]:
# Sum of a matric:
A.sum()

562

In [147]:
# Sum a single row
A[1].sum()

71

In [166]:
# Sum a single Column:
A[:,1].sum()

76

In [169]:
# Find Max of a column:
A[:,2].max()

112

In [170]:
# Find min of a column:
A[:,2].min()

0

In [171]:
# Find mean of matrix
A.mean()

46.833333333333336

In [178]:
A

array([[  0,   0,   0,   0],
       [ 50,   6,   7,   8],
       [ 59,  70, 112, 250]])

In [180]:
# max of a row:
A[2].max()

250